# Generated by Django 4.1.3 on 2022-11-03 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcommande',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livre',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
