# Generated by Django 4.1.3 on 2022-11-03 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livres', '0002_commande_note_historicalcommande_note_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='auteur',
            unique_together={('nom', 'prenoms')},
        ),
    ]
