# Generated by Django 4.1.3 on 2022-11-04 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livres', '0003_alter_auteur_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livre',
            name='nombre',
        ),
        migrations.AddField(
            model_name='livre',
            name='nombre_de_copies',
            field=models.IntegerField(default=1),
        ),
    ]
