# Generated by Django 4.1.3 on 2022-11-04 00:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livres', '0004_remove_livre_nombre_livre_nombre_de_copies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livre',
            name='isbn',
            field=models.CharField(max_length=13, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(code='nomatch', message="Seulement les chiffres sont acceptés. l'isbn doit etre long de 10 ou de 13 chiffres.", regex='^(?=(?:.{10}|.{13})$)[0-9]*$')]),
        ),
    ]
