# Generated by Django 4.1.3 on 2022-11-04 03:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('livres', '0005_alter_livre_isbn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='validee',
        ),
        migrations.RemoveField(
            model_name='historicalcommande',
            name='validee',
        ),
        migrations.AddField(
            model_name='commande',
            name='etat_emprunt',
            field=models.CharField(choices=[('P', 'PREMIER EMPRUNT'), ('N', 'LIVRE NON RENDU'), ('R', 'LIVRE RENDU')], default='P', max_length=1),
        ),
        migrations.AddField(
            model_name='historicalcommande',
            name='etat_emprunt',
            field=models.CharField(choices=[('P', 'PREMIER EMPRUNT'), ('N', 'LIVRE NON RENDU'), ('R', 'LIVRE RENDU')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='commande',
            name='matricule',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, to_field='matricule'),
        ),
    ]
