# Generated by Django 4.1.3 on 2022-11-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livres', '0006_remove_commande_validee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='etat_emprunt',
        ),
        migrations.RemoveField(
            model_name='historicalcommande',
            name='etat_emprunt',
        ),
        migrations.AddField(
            model_name='commande',
            name='emprunt_en_cours',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalcommande',
            name='emprunt_en_cours',
            field=models.BooleanField(default=True),
        ),
    ]
