# Generated by Django 4.1.3 on 2022-11-04 04:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.RegexValidator(code='noinp', message='Vous devez utiliser un email qui se termine par @inphb.ci', regex='^[\\w\\d_\\-.]+@inphb.ci$')], verbose_name='adresse email'),
        ),
    ]
